"""
Pytest configuration and fixtures for drf-social-oauth2 tests.
"""

import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'drf_social_oauth2.test_settings')

import django
django.setup()

from model_bakery import baker
from oauth2_provider.models import TokenChecksumField


# Register a custom generator for TokenChecksumField
# This field is auto-generated by django-oauth-toolkit 2.x based on the token value
baker.generators.add(TokenChecksumField, lambda: '')
