"""
Pytest configuration and fixtures for drf-social-oauth2 tests.
"""

import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'drf_social_oauth2.test_settings')

import django

django.setup()

from datetime import datetime, timedelta, timezone

from django.contrib.auth.models import User
from django.db import IntegrityError
from model_bakery import baker
from oauth2_provider.models import AccessToken, Application, RefreshToken, TokenChecksumField
from pytest import fixture

# Register a custom generator for TokenChecksumField
# This field is auto-generated by django-oauth-toolkit 2.x based on the token value
baker.generators.add(TokenChecksumField, lambda: '')


@fixture(scope='function')
def user():
    """
    Creates a user in database. This is a mock user, deleted after test runs.
    """
    try:
        user = User.objects.create_user(
            username='user', email='test@email.com', password='password'
        )
    except IntegrityError:
        user = User.objects.get(
            username='user',
            email='test@email.com',
        )

    yield user
    del user


@fixture(scope='function')
def application(user):
    """
    Creates an OAuth2 application for testing.
    """
    app, _ = Application.objects.get_or_create(
        user=user,
        client_type='confidential',
        authorization_grant_type='Resource owner password-based',
        name='app',
        client_id='id',
    )

    yield app
    del app


def save(token, request):
    """
    Helper function to save tokens during tests.
    """
    u = User.objects.get(email='test@email.com')
    app, _ = Application.objects.get_or_create(
        user=u,
        client_type='confidential',
        authorization_grant_type='Resource owner password-based',
        name='app',
        client_id='id',
    )
    re_token = RefreshToken.objects.create(
        user=u,
        token=token['refresh_token'],
        application=app,
    )
    ac_token = AccessToken.objects.create(
        user=u,
        token=token['access_token'],
        scope=token['scope'],
        application=app,
        source_refresh_token=re_token,
        expires=datetime.now(tz=timezone.utc) + timedelta(seconds=token['expires_in']),
    )
    re_token.access_token = ac_token
    re_token.save()

    return ac_token
